name: yandex_mapkit_example
description: Demonstrates how to use the yandex_mapkit plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  yandex_mapkit:
    path: ../

flutter:
  assets:
    - assets/user.png
    - assets/cluster.png
    - assets/place.png
    - assets/arrow.png
    - assets/route_start.png
    - assets/route_stop_by.png
    - assets/route_end.png
  uses-material-design: true
